language: c

compiler:
  - gcc

before_script:
  - git clone https://github.com/rumpkernel/buildrump.sh
  - git clone https://github.com/rumpkernel/src-netbsd

script:
  - ( cd src-netbsd && git checkout appstack-src )
  - ( cd buildrump.sh && ./buildrump.sh -s ../src-netbsd -q -V MKPIC=no -V RUMP_KERNEL_IS_LIBC=1 -V RUMP_CURLWP=hypercall -k -N -H -F ACLFLAGS=-m32 kernelheaders fullbuild )
  - APPSTACK_SRC=$(pwd)/src-netbsd BUILDRUMP_SH=$(pwd)/buildrump.sh sh buildme.sh
  - CFLAGS=-m32 RUMPKERNDIR=$(pwd)/buildrump.sh/rump RUMPRUN_PRESENT=yes make
  - size rk.bin rk.bin.gdb

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
