language: c

compiler:
  - gcc
  # clang build runs into problems with the minios MD code
  # - clang

before_install:
 - sudo apt-get update -y
 - sudo apt-get install libxen-dev -y

script:
  - ./build-rr.sh xen -qq
  - ( cd platform/xen ; export PATH="${PATH}:$(pwd)/app-tools" ; cd tests/configure && rumprun-xen-configure ./configure && rumprun-xen-make )

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always
