language: c

compiler:
  - gcc

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm -y
  - sudo apt-get install libxen-dev -y

env:
  - PLATFORM=xen EXTRAFLAGS=
  - PLATFORM=xen EXTRAFLAGS='-- -F ACLFLAGS=-m32'
  - PLATFORM=baremetal EXTRAFLAGS='-- -F ACLFLAGS=-m32 -F ACLFLAGS=-march=i686'

script:
  - ./build-rr.sh -qq ${PLATFORM} ${EXTRAFLAGS}

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always

# Touch me to force a travis rebuild
