language: c

before_install:
 - sudo apt-get update -y
 - sudo apt-get install clang -y
 - sudo apt-get install libxen-dev -y

script:
  - ./buildxen.sh -qq
  - ( export PATH="${PATH}:$(pwd)/app-tools" ; cd tests/configure && rumprun-xen-configure ./configure && rumprun-xen-make )

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
