language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm -y
  - git submodule update --init --recursive

script:
  - ./build-rr.sh baremetal -qq -- -F ACLFLAGS=-m32 -F ACLFLAGS=-march=i686
  - ( cd platform/baremetal && make clean )
  - ( cd platform/baremetal && make RUMPRUN_PRESENT=no )
  - ( cd platform/baremetal && size rk.bin rk.bin.gdb )
  - ( cd platform/baremetal && make RUMPRUN_PRESENT=no clean )
  - ( cd platform/baremetal && make )
  - ( cd platform/baremetal && size rk.bin rk.bin.gdb )
  - ( cd platform/baremetal && make test )

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always

# Touch me to force a travis rebuild
