language: c

before_install:
 - sudo apt-get update -y
 - sudo apt-get install libxen-dev -y

script: BUILDXEN_QUIET=qq ./buildxen.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
