language: c

compiler:
  - gcc

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm -y
  - sudo apt-get install clang -y
  - git submodule update --init --recursive

script:
  - ./buildme.sh -qq -- -F ACLFLAGS=-m32
  - make clean
  - make RUMPRUN_PRESENT=no
  - size rk.bin rk.bin.gdb
  - make RUMPRUN_PRESENT=no clean
  - make
  - size rk.bin rk.bin.gdb
  - make test

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always

# Touch me to force a travis rebuild
